
import Providers from '@/components/Providers'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Appbar from '@/components/Appbar'
import { ThemeProvider } from '@/components/theme-provider'
import DataBaseTable from './database/data-table'
import { columns } from './database/columns'
import { data } from '@/lib/data'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'tt',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="container py-10 mx-auto">
      
       <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
       <Providers>
        <Appbar/>
        </Providers>
       <DataBaseTable columns={columns} data={data}></DataBaseTable>
       </ThemeProvider>{children}
     
      </body>
    </html>
  )
}
